[phases.setup]
# Use the correct syntax to define environment variables
NODE_VERSION = "22.8.0"

[phases.install]
command = "npm install --legacy-peer-deps"

[phases.install]
command = "npm install --force"

[phases.install]
command = "rm -rf node_modules package-lock.json"

