[phases.setup]
# Use the correct syntax to define environment variables
NODE_VERSION = "22.8.0"

[phases.install]
# NPM install with legacy peer deps flag to avoid dependency conflicts
command = "npm install --legacy-peer-deps"

[phases.build]
# Run the build command
command = "npm run build"

[phases.start]
# Define how to start the app
command = "npm start"

[dependencies]
# Add extra system dependencies if necessary (e.g., 'python' or 'libpq')
packages = ["python", "libpq"]
